name: Package and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Package (skip tests and gpg)
        run: mvn clean package -DskipTests -Dgpg.skip

#      - name: Run tests
#        run: mvn clean test